// <auto-generated>
// English words that contain "gh", generated from the SCOWL / Hunspell en_US word list
// plus common British spellings. Words whose "b" spelling is more common (ghee/bee, Hugh/hub…)
// were removed. See THIRD-PARTY-NOTICES.txt for the SCOWL licence. 1206 words.
// </auto-generated>
namespace Baddel.Core;

public sealed partial class EnglishLexicon
{
    private const string GhWordsData = """
        affright affrighted affrighting affrights afghan afghani afghanis afghanistan afghans aforethought afterthought afterthoughts
        aghast airfreight airtight albright alighieri alight alighted alighting alights alleghenies allegheny almightily
        almightiness almighty alright although aright arkwright armagh ataghan attenborough aught aughts aweigh
        backlight backsight baghdad bantamweight bantamweights barghest bedight bedighted bedighting bedights beghard bellingham
        benghazi benighted benightedly benightedness besought bethought bighead bigheads bighearted bigheartedness bighorn bighorns
        bight bights bingham binghamton binghi birmingham birthright birthrights blacklight bligh blight blighted
        blighter blighters blighting blights boardinghouse boardinghouses bobsleigh bobsleighs bombsight bombsights borghese borough
        boroughs bough boughpot boughs bought boughten breakthrough breakthroughs brigham bright brighten brightened
        brightener brighteners brightening brightens brighter brightest brightly brightness brightnesses brighton brights brightwork
        brougham broughams brought buckingham buckinghamshire bughouse bulghur bulghurs bullfight bullfighter bullfighters bullfighting
        bullfights bunghole bungholes burgh burghal burgher burghers burghley burleigh burroughs callaghan candlelight
        carragheen carragheens cartwright castlereagh catchweight caught chinghai chough choughs claddagh clearinghouse clearinghouses
        clough cockfight cockfighting cockfights connaught copyright copyrightable copyrighted copyrighting copyrights cough coughed
        coughing coughings coughs counterweigh counterweight counterweights countinghouse countinghouses creighton cruiserweight cruiserweights cunningham
        curagh daugherty daughter daughterly daughters daylight daylights deadlight deadlights delight delighted delightedly
        delightedness delightest delightful delightfully delighting delights denbighshire diaghilev dight dinghies dinghy distraught
        dogfight dogfights doghouse doghouses dough doughboy doughier doughiest doughiness doughnut doughnuts doughs
        doughtier doughtiest doughty doughy downright draghound draught draughtboard draughtboards draughtier draughtiest draughts
        draughtsman draughtsmanship draughtsmen draughty dreadnought dreadnoughts drogheda droplight drought droughts droughty dunghill
        dunghills dwight earthlight edinburgh egghead eggheads eight eightball eighteen eighteenmo eighteens eighteenth
        eighteenths eightfold eighth eighths eighties eightieth eightieths eightpence eights eighty enlighten enlightened
        enlightener enlightening enlightenment enlightens enough eyebright eyesight fanlight fanlights farsighted farsightedness faugh
        fearnought featherlight featherweight featherweights ferlinghetti fermanagh fight fightback fighter fighters fighting fights
        firefight firefighter firefighters firefighting firefights firelight firelighter firelighters fistfight fistfights flashlight flashlights
        flight flighted flightier flightiest flightily flightiness flightless flightpath flights flighty floodlight floodlighted
        floodlighting floodlights flyweight flyweights foghorn foghorns footlight footlights foresight foresighted foresightedly foresightedness
        forethought forethoughtful forthright forthrightly forthrightness fortnight fortnightly fortnights fotheringhay fought fraught freight
        freightage freightages freighted freighter freighters freighting freights fright frighted frighten frightened frighteners
        frightening frighteningly frightens frightful frightfully frightfulness frighting frights froghopper froghoppers fulbright furlough
        furloughed furloughing furloughs gainsborough gallagher gaslight gaslights gastight genghis ghana ghanaian gharries
        ghastlier ghastliest ghastliness ghastly ghazi ghazvanid gheber gherkin gherkins ghetto ghettoization ghettoize
        ghettoized ghettoizes ghettoizing ghettos ghibelline ghiberti ghirlandaio ghost ghosted ghosting ghostlier ghostliest
        ghostlike ghostliness ghostly ghosts ghostwrite ghostwriter ghostwriters ghostwrites ghostwriting ghostwritten ghostwrote ghoul
        ghoulish ghoulishly ghoulishness ghouls ghq ghyll ghz gingham goddaughter goddaughters gogh goodnight
        granddaughter granddaughters gunfight gunfighter gunfighters gunfights haugh haughtier haughtiest haughtily haughtiness haughty
        headlight headlights heavyweight heavyweights height heighten heightened heightening heightens heights hiccough hiccoughed
        hiccoughing hiccoughs high highball highballs highbinder highbinders highborn highboy highboys highbred highbrow
        highbrowed highbrowism highbrows highchair highchairs higher highers highest highfalutin highflier highfliers highhanded
        highhandedly highhandedness highish highland highlander highlanders highlands highlight highlighted highlighter highlighters highlighting
        highlights highline highly highness highpoint highroad highroads highs hight hightail hightailed hightailing
        hightails hightest hightstown highway highwayman highwaymen highways hindsight hoogh hooghly horselaugh horselaughs
        hough houselights hughes hughie hundredweight hundredweights infighter infighters infighting insight insightful insightfulness
        insightfulnesses insights inveigh inveighed inveighing inveighs inwrought jacklight jacklighted jacklighter jacklighting jacklights
        jughead keogh kinghood kirghistan kirghiz kirghizes kirghizia kirkcudbright knight knighted knighthead knighthood
        knighthoods knighting knightliness knightly knights lamborghini lamplight lamplighter lamplighters laoighis larghetto laugh
        laughable laughableness laughably laughed laugher laughers laughing laughingly laughingstock laughingstocks laughs laughter
        laughton leghorn leghorns leigh leighton light lighted lighten lightened lightener lighteners lightening
        lightenings lightens lighter lighterage lighterages lighterman lightermen lighters lightest lightface lightfaced lightheaded
        lightheadedly lightheadedness lightheadednesses lighthearted lightheartedly lightheartedness lighthouse lighthouses lighting lightish lightless lightly
        lightness lightning lightninged lightnings lightproof lights lightship lightships lightsome lightweight lightweights lightyear
        limbaugh limelight lindbergh longhair longhaired longhairs longhand longhorn longhorns longhouse longhouses longsighted
        lough loughs lughole lugholes magherafelt maghreb makeweight makeweights malpighi malpighiaceous manslaughter margherita
        marlborough maugham mccullough mcknight mclaughlin mcnaughton mcveigh meetinghouse meetinghouses meghan meighen merrythought
        methought microlight microlights middlesbrough middleweight middleweights midnight midnights might mightier mightiest mightily
        mightiness mights mighty millwright millwrights moghul moghuls monaghan moonlight moonlighted moonlighter moonlighters
        moonlighting moonlights mughal narghile narghiles naught naughtier naughtiest naughtily naughtiness naughts naughty
        nearsighted nearsightedly nearsightedness neigh neighbor neighbored neighborhood neighborhoods neighboring neighborliness neighborly neighbors
        neighbour neighboured neighbourhood neighbourhoods neighbouring neighbourliness neighbourly neighbours neighed neighing neighs newburgh
        nigher nighest night nightblind nightcap nightcaps nightclothes nightclub nightclubbed nightclubbing nightclubs nightdress
        nightdresses nightfall nightgown nightgowns nighthawk nighthawks nightie nighties nightingale nightingales nightjar nightjars
        nightlife nightlight nightlights nightlong nightly nightmare nightmares nightmarish nightrider nightriders nights nightshade
        nightshades nightshirt nightshirts nightspot nightspots nightstand nightstands nightstick nightsticks nighttime nightwalker nightwalkers
        nightwatchman nightwatchmen nightwear nottingham nottinghamshire nylghau nylghaus ockeghem ogham omagh onslaught onslaughts
        ought outfight outfighting outfights outfought outright outweigh outweighed outweighing outweighs overbought overflight
        overflights overnight overnights overrighteous oversight oversights overslaugh overthought overtightened overweigh overweight overwrought
        packinghouse packinghouses paperweight paperweights penlight penlights pennyweight pennyweights peterborough pigheaded pigheadedly pigheadedness
        pittsburgh playwright playwrights plight plighted plighter plighting plights plough ploughed ploughing ploughings
        ploughman ploughmen ploughs ploughshare ploughshares plughole plugholes poughkeepsie preflight prizefight prizefighter prizefighters
        prizefighting prizefights pronghorn pronghorns qinghai raleigh rayleigh refight relight relighted relightest relighting
        relights restraighten retaught rethought reweigh reweighed reweighing reweighs rewrought right righted righteous
        righteously righteousness righter rightest rightful rightfully rightfulness righting rightism rightist rightists rightly
        rightmost rightness righto rights rightsize rightsized rightsizes rightsizing rightward rightwards ringhals ringhalses
        rockingham rough roughage roughcast roughcasting roughcasts roughed roughen roughened roughening roughens rougher
        roughest roughhew roughhewn roughhouse roughhoused roughhouses roughhousing roughing roughish roughly roughneck roughnecked
        roughnecking roughnecks roughness roughrider roughriders roughs roughshod roxburgh safelight scarborough searchlight searchlights
        senghor sennight shanghai shanghaied shanghaiing shanghais sheugh shillelagh shillelaghs shipwright shipwrights shortsighted
        shortsightedly shortsightedness sidelight sidelights sigh sighed sigher sighing sighs sight sighted sightedness
        sighting sightings sightless sightlessly sightlessness sightlessnesses sightlier sightliest sightliness sightly sightread sights
        sightseeing sightseer sightseers singh singhalese skintight skylight skylighted skylights slagheap slagheaps slaughter
        slaughtered slaughterer slaughterers slaughterhouse slaughterhouses slaughtering slaughters sleigh sleighed sleighing sleighs sleight
        sleights slight slighted slighter slightest slighting slightingly slightly slightness slights slough sloughed
        sloughier sloughiest sloughing sloughs sloughy songhai songhua sorghum sough soughed soughing soughs
        sought sourdough sourdoughs spaceflight spaceflights spaghetti spotlight spotlighted spotlighting spotlights sprightlier sprightliest
        sprightliness sprightly springhalt springhead springhouse stagefright staghound staghounds starlight steamtight stepdaughter stepdaughters
        sticktight sticktights stoplight stoplights straight straightaway straightaways straightedge straightedges straighten straightened straightener
        straighteners straightening straightens straighter straightest straightforward straightforwardly straightforwardness straightforwards straightly straightness straights
        straightway streetlight streetlights stringhalt stronghold strongholds sunlight superdreadnought superhighway superhighways taillight taillights
        taught tealight tealights thigh thighbone thighbones thighs thorough thoroughbred thoroughbreds thorougher thoroughest
        thoroughfare thoroughfares thoroughgoing thoroughly thoroughness thoroughpaced thoroughwort thoroughworts though thought thoughtful thoughtfully
        thoughtfulness thoughtless thoughtlessly thoughtlessness thoughts through throughout throughput tight tighten tightened tightener
        tighteners tightening tightens tighter tightest tightfisted tightfitting tightlipped tightly tightness tightrope tightropes
        tights tightwad tightwads tombaugh tonight topflight torchlight tough toughed toughen toughened toughener
        tougheners toughening toughens tougher toughest toughie toughies toughing toughly toughness toughs trothplight
        trough troughs tughrik tughriks twilight ugh uighur ultrahigh ultralight ultralights uncaught underweight
        unenlightened unenlightening unfought unknightly unlighted unneighborly unploughed unrighteous unrighteousness unsighted unsightlier unsightliest
        unsightliness unsightly unsought untaught unthought unthoughtful unweighed unweighted upright uprightly uprightness uprights
        uptight usquebaugh vaughan vaughn wainwright wainwrights walsingham watertight waugh weathertight weeknight weeknights
        weigh weighbridge weighbridges weighed weighing weighs weight weighted weightier weightiest weightily weightiness
        weighting weightings weightless weightlessly weightlessness weightlifter weightlifters weightlifting weights weighty welterweight welterweights
        westinghouse wheelwright wheelwrights wight wights windowlight windtight wright wrights wrongheaded wrongheadedly wrongheadedness
        wrought yataghan yataghans yoghurt yoghurts yukaghir
        """;
}
